server:
  port: 9192

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/hotel_manage_db
    username : root
    password : 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql : true


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
